# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-11 17:06
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_indexgoodsbanner_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsimage',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='goodssku',
            name='goods',
        ),
        migrations.AddField(
            model_name='goodssku',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, verbose_name='商品详情'),
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsImage',
        ),
    ]
