# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-11 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190412_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品SPU'),
            preserve_default=False,
        ),
    ]
